### ISSUE TITLE
Codify model restrictions and defaults

### ISSUE THREAD

**Issue by RastislavTuranyi** [pace-neutrons/resins#23]
Currently, the `restrictions` and `defaults` that any given model requires are completely free-form and undefined - the only requirement are `ModelData.restrictions` and `ModelData.defaults` which create a unified interface for users to use. However, the meaning of these is in fact unclear; e.g. is a list of three values for `e_init` `restrictions` the three allowed values or the (stop, start, step) tuple?

There is a way to improve all aspects of this by adding to the YAML file spec the fact that `restrictions` and `defaults` must be specified as dictionaries, i.e.:

```
parameters:
    defaults:
        e_init: [100, 1000]
        chopper_frequency: !!set {60, 120, 180}
```

which can then be used directly without accessing any underlying attributes. Further, as shown above, it can be made a part of the spec that a YAML `list` is interpreted as a (start, stop, step) tuple, as in `range`, and a YAML `set` is interpreted as a list of discrete values.
